### ISSUE TITLE
Create Django project and app

### ISSUE THREAD

**Issue by ryanharper827** [ryanharper827/ResumeSite#1]
## Idea
To start making an app we need the base app. Also, the secret key needs to be hidden.
## Todo
- [x] Create Django project
- [x] Create Django app
- [x] Hide secret key
