### ISSUE TITLE
💻 Create Models

### ISSUE THREAD

**Issue by ryanharper827** [ryanharper827/ResumeSite#1]
## Idea
Create the models for the site's database
## Todo
- [x] UserProfile
  - [x] First name
  - [x] Last name
  - [x] Email
  - [x] Phone Number
  - [x] Job title
  - [x] Github URL
  - [x] Birthdate (to calculate age)
  - [x] Resume file
  - [x] About me (rich text)
- [x] Skills
  - [x] Name
  - [x] Score
  - [x] Rank
- [x] Experience
  - [x] Job title
  - [x] Employer
  - [x] Start date
  - [x] End date (could also be Present)
  - [x] Description (rich text)
- [x] Education
  - [x] Degree
  - [x] School
  - [x] Start year
  - [x] End year (could also be Present)
  - [x] Description (rich text)
- [x] Portfolio
  - [x] Title
  - [x] Technologies used
  - [x] Description (rich text)
  - [x] Photo
- [x] Reference
  - [x] Name
  - [x] Job title
  - [x] Employer
  - [x] Quote
- [x] Contact
  - [x] Name
  - [x] Email
  - [x] Message

**Comment by ryanharper827** [comment]
Created all models listed above.
