### ISSUE TITLE
Create view for main page

### ISSUE THREAD

**Issue by ryanharper827** [ryanharper827/ResumeSite#11]
## Idea
Just getting the template into Django and making sure nothing is visually wrong.

## Todo
- [ ] Import index.html
- [ ] Import statics
- [ ] Create template view
- [ ] Verify the website appears properly like the template
