### ISSUE TITLE
Create models

### ISSUE THREAD

**Issue by ryanharper827** [ryanharper827/ResumeSite#2]
## Idea
Create models needed for the site to function properly.
## Todo
- [x] Skills
  - [x] Name
  - [x] Score
  - [x] Level (Beginner, Advance, Expert, Master)
- [x] User (builtin)
  - [x] First name
  - [x] Last name
  - [x] Email address
- [x] Userprofile
  - [x] Job title
  - [x] Resume file
  - [x] Address (general area? may need to rethink that address thing lol)
  - [x] Linkedin URL
  - [x] Github URL
  - [x] Bio
  - [x] Phone Number 
  - [x] Birthday (to calculate age)
- [x] Work Experience
  - [x] Job title
  - [x] Company name
  - [x] Company URL
  - [x] Date started
  - [x] Date ended (can be Present, maybe if null then Present?)
  - [x] Description
- [x] Education
  - [x] Degree name
  - [x] Institution name
  - [x] Year started
  - [x] Year ended
  - [x] description
- [x] Portfolio
  - [x] Title
  - [x] Decription
  - [x] Keywords
  - [x] Picture
  - [x] URL
- [x] References
  - [x] First name
  - [x] Last name
  - [x] Job title
  - [x] Company or Institution
  - [x] Quote
  - [x] Picture
- [x] Contact
  - [x] Name
  - [x] Email
  - [x] Message

**Comment by ryanharper827** [comment]
Determining which models are needed

**Comment by ryanharper827** [comment]
Using the site from #4
