### ISSUE TITLE
💻 Make deployable to Heroku

### ISSUE THREAD

**Issue by ryanharper827** [ryanharper827/ResumeSite#2]
## Idea
Make it so this site can be deployed to Heroku automatically.
## Todo
- [x] Create Procfile
- [x] Add host to ALLOWED_HOSTS
- [x] Use django-on-heroku
- [x] Set environment variables on Heroku
- [x] Verify this doesn't break testing
## Links
https://realpython.com/django-hosting-on-heroku/
https://pypi.org/project/django-on-heroku/

**Comment by ryanharper827** [comment]
Didn't break local testing.

**Comment by ryanharper827** [comment]
django-on-heroku is broken for my implementation, trying django-heroku

**Comment by ryanharper827** [comment]
App fully functional on Heroku!
