### ISSUE TITLE
💻 Secure Project

### ISSUE THREAD

**Issue by ryanharper827** [ryanharper827/ResumeSite#3]
## Idea
This project should be secured before deployed to prevent hacking.
## Todo
- [x] Use SSL
- [x] Change admin URL
- [x] Use 'django-admin-honeypot'
- [ ] Use 2FA
- [x] Verify production has `DEBUG` off
- [x] Use django-admin-env-notice to make sure I'm not affecting production code
- [x] Run `python manage.py check --deploy` to check for security errors
- [x] Run through https://djcheckup.com/pony/ to get security score

**Comment by ryanharper827** [comment]
2FA is limited by this project's next release: https://github.com/jazzband/django-two-factor-auth

**Comment by ryanharper827** [comment]
`python manage.py check --deploy` is suggesting I use SSL, which I'll have to set up tomorrow when I also set up #2. Once the project is secured (2FA can come later) I will run it through djcheckup and see what else can be improved.

**Comment by ryanharper827** [comment]
Looks like Heroku takes care of SSL for me. Will have to test that out.

**Comment by ryanharper827** [comment]
Results of djcheckup will be made into its own issue.
Results: https://djcheckup.com/check/2ceb0273-678e-406d-a6d6-82911ed30758/
